# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foundation_tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The name of the City.', max_length=63, null=True, verbose_name='Name')),
                ('owners', models.ManyToManyField(blank=True, help_text='The owners of this workspace.', related_name='workspace_owners_foundation_tenant_workspace_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Workspaces',
                'verbose_name': 'Workspace',
                'db_table': 'biz_workspaces',
            },
        ),
    ]
