# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-29 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='docxpresso_file',
            field=models.ForeignKey(blank=True, help_text='The files uploaded by a User.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foundation_tenant_document_file_related', to='foundation_tenant.TenantFileUpload'),
        ),
    ]
