# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='help',
            field=models.CharField(blank=True, help_text='The title of this question.', max_length=511, null=True, verbose_name='Help'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, help_text='The title of this question.', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
