# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_ready',
            field=models.BooleanField(default=False, help_text='Indicates whether this document has been generated and ready for consumption or not.', verbose_name='Is Ready'),
        ),
    ]
