# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantme',
            name='challenges_becoming_entrepreneur',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'My health'), (2, 'Childcare'), (3, 'Transportation'), (4, 'Lack of Family support'), (5, 'Language skills'), (6, 'Other')], default=1, help_text='Enter challenges in becoming entrepreneur.', verbose_name='Challenges becoming Entrepreneur'),
        ),
        migrations.AlterField(
            model_name='tenantme',
            name='education_or_training_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Highschool'), (2, 'Post-Secondary'), (3, 'Private career training'), (4, 'Specialized employment program'), (5, 'Other')], default=1, help_text='The employment status of this User.', verbose_name='Education or Training Status'),
        ),
        migrations.AlterField(
            model_name='tenantme',
            name='employment_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'employed full time'), (2, 'employed part time'), (3, 'underemployed'), (4, 'unemployed'), (5, 'receiving disability benefits'), (6, 'retired'), (7, 'Other')], default=1, help_text='The employment status of this User.', verbose_name='Employment Status'),
        ),
        migrations.AlterField(
            model_name='tenantme',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Another'), (4, 'Other')], default=1, help_text='The gender this User identifies as.', verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='tenantme',
            name='level_of_education',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Another'), (4, 'Other')], default=1, help_text='The highest level of education this User has attained.', verbose_name='Highest Level of Education'),
        ),
        migrations.AlterField(
            model_name='tenantme',
            name='place_of_birth',
            field=models.CharField(blank=True, choices=[('United States', 'United States'), ('Canada', 'Canada'), ('Zimbabwe', 'Zimbabwe'), ('Other', 'Other')], help_text='The place this User was born.', max_length=127, null=True, verbose_name='Place of Birth'),
        ),
        migrations.AlterField(
            model_name='tenantme',
            name='why_be_entrepreneur',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Highschool'), (2, 'Post-Secondary'), (3, 'Private career training'), (4, 'Specialized employment program'), (5, 'Other')], default=1, help_text='Enter why the User wants to be an entrepreneur.', verbose_name='Why be an Entrepreneur'),
        ),
    ]
