# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 18:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0002_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='stage_num',
            field=models.PositiveSmallIntegerField(default=1, help_text='Track what stage this Module belongs to.', verbose_name='Stage Number'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='owners',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='The owners of this workspace.', related_name='workspace_owners_foundation_tenant_workspace_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
