# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0002_document_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='previous_exercise_id',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='The previous exercise ID to load up.', null=True, verbose_name='Previous Exercise ID'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='next_exercise_id',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='The exercise ID to load up next.', null=True, verbose_name='Next Exercise ID'),
        ),
    ]
