# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 18:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0002_auto_20161119_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dependency',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{}', help_text='The dependency code this question has to link with other questions.', verbose_name='Dependency'),
        ),
    ]
