# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-21 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='me',
        ),
        migrations.AddField(
            model_name='notification',
            name='closures',
            field=models.ManyToManyField(blank=True, help_text='The users who closed the notification.', related_name='foundation_tenant_notification_notification_closures_related', to='foundation_tenant.TenantMe'),
        ),
    ]
