# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 22:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0003_auto_20161102_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='The name of this Document Type.', max_length=127, null=True, verbose_name='Text')),
            ],
            options={
                'db_table': 'biz_document_types',
                'verbose_name_plural': 'Document Types',
                'verbose_name': 'Document Type',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(blank=True, default=0, help_text='The number to display for this question.', null=True, verbose_name='Number')),
                ('title', models.CharField(blank=True, help_text='The title of this question.', max_length=127, null=True, verbose_name='Title')),
                ('help', models.CharField(blank=True, help_text='The title of this question.', max_length=255, null=True, verbose_name='Help')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(blank={}, help_text='The content to populate the question with.', null=True, verbose_name='Content')),
                ('template_id', models.PositiveSmallIntegerField(blank=True, default=0, help_text='The template ID to load up for the view.', null=True, verbose_name='Template ID')),
                ('document_type', models.ForeignKey(blank=True, help_text='The document type this question belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_document_typefoundation_tenant_question_related', to='foundation_tenant.DocumentType')),
            ],
            options={
                'db_table': 'biz_questions',
                'verbose_name_plural': 'Questions',
                'verbose_name': 'Question',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(blank={}, help_text='The content to populate the QuestionAnswer with.', null=True, verbose_name='content')),
                ('document', models.ForeignKey(blank=True, help_text='The document this answer belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_answer_document_foundation_tenant_questionanswer_related', to='foundation_tenant.Document')),
                ('question', models.ForeignKey(blank=True, help_text='The question this option belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_answer_question_foundation_tenant_questionanswer_related', to='foundation_tenant.Question')),
                ('workspace', models.ForeignKey(blank=True, help_text='The workspace this answer belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_answer_workspace_foundation_tenant_questionanswer_related', to='foundation_tenant.Workspace')),
            ],
            options={
                'db_table': 'biz_question_answers',
                'verbose_name_plural': 'Question Answers',
                'verbose_name': 'Question Answer',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_id', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Alternative ID to use.', null=True, verbose_name='Alternate ID')),
                ('order_num', models.PositiveSmallIntegerField(blank=True, default=0, help_text='The order number to sort option by.', null=True, verbose_name='Order Number')),
                ('text', models.CharField(blank=True, help_text='The title of this QuestionOption.', max_length=63, null=True, verbose_name='Text')),
                ('value', models.CharField(blank=True, help_text='The title of this QuestionOption.', max_length=63, null=True, verbose_name='Value')),
                ('help', models.CharField(blank=True, help_text='The title of this question.', max_length=255, null=True, verbose_name='Help')),
                ('parent', models.ForeignKey(blank=True, help_text='The parent option this option belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_option_parent_foundation_tenant_questionoption_related', to='foundation_tenant.QuestionOption')),
                ('question', models.ForeignKey(blank=True, help_text='The question this option belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_option_question_foundation_tenant_questionoption_related', to='foundation_tenant.Question')),
            ],
            options={
                'db_table': 'biz_question_options',
                'verbose_name_plural': 'Question Options',
                'verbose_name': 'Question Option',
                'ordering': ('order_num',),
            },
        ),
        migrations.AlterField(
            model_name='module',
            name='colour',
            field=models.CharField(blank=True, help_text='The colour to display for this Module.', max_length=31, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, default='', help_text='A description of this Module.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='module',
            name='icon',
            field=models.CharField(blank=True, help_text='The icon to display for this Module.', max_length=31, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(blank=True, help_text='The title of this Module.', max_length=127, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, help_text='The name of the City.', max_length=127, null=True, verbose_name='Introduction Title'),
        ),
    ]
