# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0003_auto_20161110_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='owners',
        ),
        migrations.AddField(
            model_name='workspace',
            name='mes',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='The User profile owners of this workspace.', related_name='workspace_mes_foundation_tenant_workspace_related', to='foundation_tenant.TenantMe'),
        ),
    ]
