# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-22 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0003_auto_20170121_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(blank=True, help_text='The icon of this notification.', max_length=31, null=True, verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type_of',
            field=models.CharField(blank=True, help_text='The colour of this notification.', max_length=15, null=True, verbose_name='Colour'),
        ),
    ]
