# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 18:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0003_question_dependency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{}', help_text='The options to populate the question with.', verbose_name='Options'),
        ),
    ]
