# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0004_auto_20161204_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantme',
            name='why_be_entrepreneur',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'I want to work for myself'), (2, 'I want to control my own schedule'), (3, 'I want to make more money'), (4, 'I want better work-life balance'), (5, 'I have a business idea that I want to try out'), (6, 'Other')], default=1, help_text='Enter why the User wants to be an entrepreneur.', verbose_name='Why be an Entrepreneur'),
        ),
    ]
