# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 21:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0004_auto_20161120_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='validation',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{}', help_text='The validation identification used for this question.', verbose_name='Validation'),
        ),
    ]
