# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0004_auto_20161110_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='module',
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
        migrations.RemoveField(
            model_name='slide',
            name='next_exercise_id',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='next_slide_id',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='page_num',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='previous_exercise_id',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='previous_slide_id',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
