# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-22 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0004_auto_20170121_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='entrepreneurs_average_stage_num',
            field=models.FloatField(default=0, help_text='Keep track of the average stage number that most entrepeneurs that belong this tag fall under.', null=True, verbose_name='Entrepreneurs Average Stage'),
        ),
        migrations.AddField(
            model_name='tag',
            name='entrepreneurs_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Keep track of how many entrepreneurs that are assigned to this tag.', null=True, verbose_name='entrepreneurs_count'),
        ),
    ]
