# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0005_auto_20161204_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantme',
            name='has_owned_business',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Other')], default=1, help_text='Enter has owned business.', verbose_name='Has Owned Business'),
        ),
    ]
