# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foundation_tenant', '0005_geocoordinate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('alternate_name', models.CharField(blank=True, help_text='An alias for the item.', max_length=255, null=True, verbose_name='Alternate Name')),
                ('description', models.TextField(blank=True, help_text='A short description of the item.', null=True, verbose_name='Description')),
                ('main_entity_of_page', models.URLField(blank=True, help_text='Indicates a page for which this thing is the main entity being described.', null=True, verbose_name='Main Entity Of Page')),
                ('name', models.CharField(blank=True, help_text='The name of the item.', max_length=255, null=True, verbose_name='Name')),
                ('same_as', models.URLField(blank=True, help_text="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Freebase page, or official website.", null=True, verbose_name='Same As')),
                ('url', models.URLField(blank=True, help_text='URL of the item.', null=True, verbose_name='URL')),
                ('fax_number', models.CharField(blank=True, help_text='The fax number.', max_length=31, null=True, verbose_name='Fax Number')),
                ('global_location_number', models.CharField(blank=True, help_text='The <a href="http://www.gs1.org/gln">Global Location Number</a> (GLN, sometimes also referred to as International Location Number or ILN) of the respective organization, person, or place. The GLN is a 13-digit number used to identify parties and physical locations.', max_length=255, null=True, verbose_name='Global Location Number')),
                ('has_map', models.URLField(blank=True, help_text='A URL to a map of the place.', null=True, verbose_name='Has Map')),
                ('isic_v4', models.CharField(blank=True, help_text='The International Standard of Industrial Classification of All Economic Activities (ISIC), Revision 4 code for a particular organization, business person, or place.', max_length=255, null=True, verbose_name='ISIC V4')),
                ('telephone', models.CharField(blank=True, help_text='The telephone number.', max_length=31, null=True, verbose_name='Telephone')),
                ('address', models.ForeignKey(blank=True, help_text='Physical address of the item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_address_foundation_tenant_country_related', to='foundation_tenant.PostalAddress')),
                ('geo', models.ForeignKey(blank=True, help_text='The geo coordinates of the place.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_geo_foundation_tenant_country_related', to='foundation_tenant.GeoCoordinate')),
                ('image', models.ForeignKey(blank=True, help_text='An image of the item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thing_image_foundation_tenant_country_related', to='foundation_tenant.TenantImageUpload')),
                ('logo', models.ForeignKey(blank=True, help_text='An associated logo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_logo_foundation_tenant_country_related', to='foundation_tenant.TenantImageUpload')),
                ('opening_hours_specification', models.ManyToManyField(blank=True, help_text='The hours during which this service or contact is available.', related_name='place_hours_available_foundation_tenant_country_related', to='foundation_tenant.OpeningHoursSpecification')),
                ('owner', models.ForeignKey(blank=True, help_text='The user whom owns this thing.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(blank=True, help_text='A photograph of this place.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_photo_foundation_tenant_country_related', to='foundation_tenant.TenantImageUpload')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'verbose_name': 'Country',
                'db_table': 'biz_countries',
            },
        ),
    ]
