# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0005_auto_20161103_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='video',
        ),
        migrations.AddField(
            model_name='slide',
            name='video_url',
            field=models.URLField(blank=True, help_text='The URL of our video for this slide.', null=True, verbose_name='Video URL'),
        ),
    ]
