# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-23 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0005_auto_20170122_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspace',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
