# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 15:12
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0006_auto_20161103_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='question_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, help_text='The question IDs that belong to this exercise.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(blank=True, help_text='The name of this exercise.', max_length=255, null=True, verbose_name='Introduction Title'),
        ),
    ]
