# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0006_auto_20161123_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
