# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0007_auto_20161105_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='document_type',
            field=models.ForeignKey(blank=True, help_text='The document type that this Exercises questions belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_document_type_foundation_tenant_exercise_related', to='foundation_tenant.DocumentType'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(blank=True, help_text='The name of this exercise.', max_length=127, null=True, verbose_name='Introduction Title'),
        ),
    ]
