# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 00:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0009_module_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='program',
        ),
        migrations.AddField(
            model_name='module',
            name='nodes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank={}, help_text='The slides and Questions nodes to be processed by this module.', null=True, verbose_name='Nodes'),
        ),
    ]
