# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 15:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0011_auto_20161107_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='nodes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='', help_text='The slides and Questions nodes to be processed by this module.', verbose_name='Nodes'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='', help_text='The content to populate the question with.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='', help_text='The options to populate the question with.', verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{}', help_text='The content to populate the QuestionAnswer with.', verbose_name='content'),
        ),
    ]
