# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0013_auto_20161107_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='has_pending_review',
            field=models.BooleanField(default=False, help_text='Indicates whether this document needs to be reviewed by staff member.', verbose_name='Has Pending Review'),
        ),
    ]
