# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_tenant', '0014_document_has_pending_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='has_pending_review',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_ready',
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created Status'), (2, 'Pending Review Status'), (3, 'Ready Status')], default=1, help_text='The status of this Document.', verbose_name='Status'),
        ),
    ]
