# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=63, unique=True)),
                ('banned_on', models.DateField(auto_now_add=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=127, null=True)),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'biz_banned_domains',
            },
        ),
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('banned_on', models.DateField(auto_now_add=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=127, null=True)),
            ],
            options={
                'ordering': ('address',),
                'db_table': 'biz_banned_ips',
            },
        ),
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=63, unique=True)),
                ('banned_on', models.DateField(auto_now_add=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=127, null=True)),
            ],
            options={
                'ordering': ('text',),
                'db_table': 'biz_banned_words',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('alternate_name', models.CharField(blank=True, help_text='An alias for the item.', max_length=255, null=True, verbose_name='Alternate Name')),
                ('description', models.TextField(blank=True, help_text='A short description of the item.', null=True, verbose_name='Description')),
                ('main_entity_of_page', models.URLField(blank=True, help_text='Indicates a page for which this thing is the main entity being described.', null=True, verbose_name='Main Entity Of Page')),
                ('name', models.CharField(blank=True, help_text='The name of the item.', max_length=255, null=True, verbose_name='Name')),
                ('same_as', models.URLField(blank=True, help_text="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Freebase page, or official website.", null=True, verbose_name='Same As')),
                ('url', models.URLField(blank=True, help_text='URL of the item.', null=True, verbose_name='URL')),
            ],
            options={
                'db_table': 'biz_brands',
                'verbose_name_plural': 'Brands',
                'verbose_name': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='PublicContactPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('alternate_name', models.CharField(blank=True, help_text='An alias for the item.', max_length=255, null=True, verbose_name='Alternate Name')),
                ('description', models.TextField(blank=True, help_text='A short description of the item.', null=True, verbose_name='Description')),
                ('main_entity_of_page', models.URLField(blank=True, help_text='Indicates a page for which this thing is the main entity being described.', null=True, verbose_name='Main Entity Of Page')),
                ('name', models.CharField(blank=True, help_text='The name of the item.', max_length=255, null=True, verbose_name='Name')),
                ('same_as', models.URLField(blank=True, help_text="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Freebase page, or official website.", null=True, verbose_name='Same As')),
                ('url', models.URLField(blank=True, help_text='URL of the item.', null=True, verbose_name='URL')),
                ('area_served', models.CharField(blank=True, help_text='The geographic area where a service or offered item is provided.', max_length=127, null=True, verbose_name='Area Served')),
                ('contact_type', models.CharField(blank=True, help_text='A person or organization can have different contact points, for different purposes. For example, a sales contact point, a PR contact point and so on. This property is used to specify the kind of contact point.', max_length=127, null=True, verbose_name='Contact Type')),
                ('email', models.EmailField(blank=True, help_text='Email address.', max_length=254, null=True, verbose_name='Email')),
                ('fax_number', models.CharField(blank=True, help_text='The fax number.', max_length=31, null=True, verbose_name='Fax Number')),
                ('product_supported', models.CharField(blank=True, help_text='The product or service this support contact point is related to (such as product support for a particular product line). This can be a specific product or product line (e.g. "iPhone") or a general category of products or services (e.g. "smartphones").', max_length=31, null=True, verbose_name='Product Supported')),
                ('telephone', models.CharField(blank=True, help_text='The telephone number.', max_length=31, null=True, verbose_name='Telephone')),
            ],
            options={
                'db_table': 'biz_contact_points',
                'verbose_name_plural': 'Contact Points',
                'verbose_name': 'Contact Point',
            },
        ),
        migrations.CreateModel(
            name='PublicCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('alternate_name', models.CharField(blank=True, help_text='An alias for the item.', max_length=255, null=True, verbose_name='Alternate Name')),
                ('description', models.TextField(blank=True, help_text='A short description of the item.', null=True, verbose_name='Description')),
                ('main_entity_of_page', models.URLField(blank=True, help_text='Indicates a page for which this thing is the main entity being described.', null=True, verbose_name='Main Entity Of Page')),
                ('name', models.CharField(blank=True, help_text='The name of the item.', max_length=255, null=True, verbose_name='Name')),
                ('same_as', models.URLField(blank=True, help_text="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Freebase page, or official website.", null=True, verbose_name='Same As')),
                ('url', models.URLField(blank=True, help_text='URL of the item.', null=True, verbose_name='URL')),
                ('fax_number', models.CharField(blank=True, help_text='The fax number.', max_length=31, null=True, verbose_name='Fax Number')),
                ('global_location_number', models.CharField(blank=True, help_text='The <a href="http://www.gs1.org/gln">Global Location Number</a> (GLN, sometimes also referred to as International Location Number or ILN) of the respective organization, person, or place. The GLN is a 13-digit number used to identify parties and physical locations.', max_length=255, null=True, verbose_name='Global Location Number')),
                ('has_map', models.URLField(blank=True, help_text='A URL to a map of the place.', null=True, verbose_name='Has Map')),
                ('isic_v4', models.CharField(blank=True, help_text='The International Standard of Industrial Classification of All Economic Activities (ISIC), Revision 4 code for a particular organization, business person, or place.', max_length=255, null=True, verbose_name='ISIC V4')),
                ('telephone', models.CharField(blank=True, help_text='The telephone number.', max_length=31, null=True, verbose_name='Telephone')),
            ],
            options={
                'db_table': 'biz_countries',
                'verbose_name_plural': 'Countries',
                'verbose_name': 'Country',
            },
        ),
        migrations.CreateModel(
            name='PublicFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('datafile', models.FileField(blank=True, help_text='An file of the upload.', null=True, upload_to='upload', verbose_name='File')),
                ('owner', models.ForeignKey(blank=True, help_text='The user whom owns this object.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'biz_public_file_uploads',
                'verbose_name_plural': 'File Uploads',
                'verbose_name': 'File Upload',
            },
        ),
        migrations.CreateModel(
            name='PublicGeoCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('alternate_name', models.CharField(blank=True, help_text='An alias for the item.', max_length=255, null=True, verbose_name='Alternate Name')),
                ('description', models.TextField(blank=True, help_text='A short description of the item.', null=True, verbose_name='Description')),
                ('main_entity_of_page', models.URLField(blank=True, help_text='Indicates a page for which this thing is the main entity being described.', null=True, verbose_name='Main Entity Of Page')),
                ('name', models.CharField(blank=True, help_text='The name of the item.', max_length=255, null=True, verbose_name='Name')),
                ('same_as', models.URLField(blank=True, help_text="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Freebase page, or official website.", null=True, verbose_name='Same As')),
                ('url', models.URLField(blank=True, help_text='URL of the item.', null=True, verbose_name='URL')),
                ('address', models.CharField(blank=True, help_text='Physical address of the item.', max_length=255, null=True, verbose_name='Address')),
                ('address_country', models.CharField(blank=True, help_text='The country. For example, USA. You can also provide the two-letter <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements">ISO 3166-1 alpha-2</a> country code.', max_length=255, null=True, verbose_name='Address Country')),
                ('elevation', models.FloatField(blank=True, default=0.0, help_text='The elevation of a location (<a href="https://en.wikipedia.org/wiki/World_Geodetic_System">WGS 84</a>).', verbose_name='Elevation')),
                ('latitude', models.FloatField(blank=True, default=0.0, help_text='The latitude of a location. For example 37.42242 (<a href="https://en.wikipedia.org/wiki/World_Geodetic_System">WGS 84</a>).', verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, default=0.0, help_text='The longitude of a location. For example -122.08585 (<a href="https://en.wikipedia.org/wiki/World_Geodetic_System">WGS 84</a>).', verbose_name='Longitude')),
                ('postal_code', models.CharField(blank=True, help_text='The postal code. For example, 94043.', max_length=127, null=True, verbose_name='Postal Code')),
            ],
            options={
                'db_table': 'biz_geocoordinates',
                'verbose_name_plural': 'GeoCoordinates',
                'verbose_name': 'GeoCoordinate',
            },
        ),
        migrations.CreateModel(
            name='PublicImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('imagefile', models.ImageField(blank=True, help_text='An image of the upload.', null=True, upload_to='upload', verbose_name='Image')),
                ('owner', models.ForeignKey(blank=True, help_text='The user whom owns this object.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'biz_public_image_uploads',
                'verbose_name_plural': 'Image Uploads',
                'verbose_name': 'Image Upload',
            },
        ),
        migrations.CreateModel(
            name='PublicLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('alternate_name', models.CharField(blank=True, help_text='An alias for the item.', max_length=255, null=True, verbose_name='Alternate Name')),
                ('description', models.TextField(blank=True, help_text='A short description of the item.', null=True, verbose_name='Description')),
                ('main_entity_of_page', models.URLField(blank=True, help_text='Indicates a page for which this thing is the main entity being described.', null=True, verbose_name='Main Entity Of Page')),
                ('name', models.CharField(blank=True, help_text='The name of the item.', max_length=255, null=True, verbose_name='Name')),
                ('same_as', models.URLField(blank=True, help_text="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Freebase page, or official website.", null=True, verbose_name='Same As')),
                ('url', models.URLField(blank=True, help_text='URL of the item.', null=True, verbose_name='URL')),
                ('image', models.ForeignKey(blank=True, help_text='An image of the item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thing_image_foundation_public_publiclanguage_related', to='foundation_public.PublicImageUpload')),
                ('owner', models.ForeignKey(blank=True, help_text='The user whom owns this thing.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'biz_languages',
                'verbose_name_plural': 'Languages',
                'verbose_name': 'Language',
            },
        ),
        migrations.CreateModel(
            name='PublicOpeningHoursSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('alternate_name', models.CharField(blank=True, help_text='An alias for the item.', max_length=255, null=True, verbose_name='Alternate Name')),
                ('description', models.TextField(blank=True, help_text='A short description of the item.', null=True, verbose_name='Description')),
                ('main_entity_of_page', models.URLField(blank=True, help_text='Indicates a page for which this thing is the main entity being described.', null=True, verbose_name='Main Entity Of Page')),
                ('name', models.CharField(blank=True, help_text='The name of the item.', max_length=255, null=True, verbose_name='Name')),
                ('same_as', models.URLField(blank=True, help_text="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Freebase page, or official website.", null=True, verbose_name='Same As')),
                ('url', models.URLField(blank=True, help_text='URL of the item.', null=True, verbose_name='URL')),
                ('closes', models.CharField(blank=True, help_text='The closing hour of the place or service on the given day(s) of the week.', max_length=5, null=True, verbose_name='Closes')),
                ('day_of_week', models.CharField(blank=True, help_text='The day of the week for which these opening hours are valid.', max_length=2, null=True, verbose_name='Day Of Week')),
                ('opens', models.CharField(blank=True, help_text='The opening hour of the place or service on the given day(s) of the week.', max_length=5, null=True, verbose_name='Opens')),
                ('valid_from', models.DateField(blank=True, help_text='The date when the item becomes valid.', null=True, verbose_name='Valid From')),
                ('valid_through', models.DateField(blank=True, help_text='The end of the validity of offer, price specification, or opening hours data.', null=True, verbose_name='Valid Through')),
                ('image', models.ForeignKey(blank=True, help_text='An image of the item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thing_image_foundation_public_publicopeninghoursspecification_related', to='foundation_public.PublicImageUpload')),
                ('owner', models.ForeignKey(blank=True, help_text='The user whom owns this thing.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'biz_opening_hours_specifications',
                'verbose_name_plural': 'Opening Hours Specifications',
                'verbose_name': 'Opening Hours Specification',
            },
        ),
        migrations.CreateModel(
            name='PublicOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('alternate_name', models.CharField(blank=True, help_text='An alias for the item.', max_length=255, null=True, verbose_name='Alternate Name')),
                ('description', models.TextField(blank=True, help_text='A short description of the item.', null=True, verbose_name='Description')),
                ('main_entity_of_page', models.URLField(blank=True, help_text='Indicates a page for which this thing is the main entity being described.', null=True, verbose_name='Main Entity Of Page')),
                ('name', models.CharField(blank=True, help_text='The name of the item.', max_length=255, null=True, verbose_name='Name')),
                ('same_as', models.URLField(blank=True, help_text="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Freebase page, or official website.", null=True, verbose_name='Same As')),
                ('url', models.URLField(blank=True, help_text='URL of the item.', null=True, verbose_name='URL')),
                ('on_trial', models.BooleanField(default=False)),
                ('paid_until', models.DateField(auto_now_add=True, null=True)),
                ('dissolution_date', models.DateField(blank=True, help_text='The date that this organization was dissolved.', null=True, verbose_name='Dissolution Date')),
                ('duns', models.CharField(blank=True, help_text='The Dun & Bradstreet DUNS number for identifying an organization or business person.', max_length=127, null=True, verbose_name='Additional Name')),
                ('email', models.EmailField(blank=True, help_text='Email address.', max_length=254, null=True, verbose_name='Email')),
                ('fax_number', models.CharField(blank=True, help_text='The fax number.', max_length=31, null=True, verbose_name='Fax Number')),
                ('founding_date', models.DateField(blank=True, help_text='The date that this organization was founded.', null=True, verbose_name='Founding Date')),
                ('global_location_number', models.CharField(blank=True, help_text='The <a href="http://www.gs1.org/gln">Global Location Number</a> (GLN, sometimes also referred to as International Location Number or ILN) of the respective organization, person, or place. The GLN is a 13-digit number used to identify parties and physical locations.', max_length=255, null=True, verbose_name='Global Location Number')),
                ('isic_v4', models.CharField(blank=True, help_text='The International Standard of Industrial Classification of All Economic Activities (ISIC), Revision 4 code for a particular organization, business person, or place.', max_length=255, null=True, verbose_name='ISIC V4')),
                ('legal_name', models.CharField(blank=True, help_text='The official name of the organization, e.g. the registered company name.', max_length=255, null=True, verbose_name='Legal Name')),
                ('naics', models.CharField(blank=True, help_text='The North American Industry Classification System (NAICS) code for a particular organization or business person.', max_length=127, null=True, verbose_name='NAICS')),
                ('tax_id', models.CharField(blank=True, help_text='The Tax / Fiscal ID of the organization or person, e.g. the TIN in the US or the CIF/NIF in Spain.', max_length=255, null=True, verbose_name='Tax ID')),
                ('telephone', models.CharField(blank=True, help_text='The telephone number.', max_length=31, null=True, verbose_name='Telephone')),
                ('vat_id', models.CharField(blank=True, help_text='The Value-added Tax ID of the organization or person.', max_length=255, null=True, verbose_name='Tax ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('alternate_name', models.CharField(blank=True, help_text='An alias for the item.', max_length=255, null=True, verbose_name='Alternate Name')),
                ('description', models.TextField(blank=True, help_text='A short description of the item.', null=True, verbose_name='Description')),
                ('main_entity_of_page', models.URLField(blank=True, help_text='Indicates a page for which this thing is the main entity being described.', null=True, verbose_name='Main Entity Of Page')),
                ('name', models.CharField(blank=True, help_text='The name of the item.', max_length=255, null=True, verbose_name='Name')),
                ('same_as', models.URLField(blank=True, help_text="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Freebase page, or official website.", null=True, verbose_name='Same As')),
                ('url', models.URLField(blank=True, help_text='URL of the item.', null=True, verbose_name='URL')),
                ('fax_number', models.CharField(blank=True, help_text='The fax number.', max_length=31, null=True, verbose_name='Fax Number')),
                ('global_location_number', models.CharField(blank=True, help_text='The <a href="http://www.gs1.org/gln">Global Location Number</a> (GLN, sometimes also referred to as International Location Number or ILN) of the respective organization, person, or place. The GLN is a 13-digit number used to identify parties and physical locations.', max_length=255, null=True, verbose_name='Global Location Number')),
                ('has_map', models.URLField(blank=True, help_text='A URL to a map of the place.', null=True, verbose_name='Has Map')),
                ('isic_v4', models.CharField(blank=True, help_text='The International Standard of Industrial Classification of All Economic Activities (ISIC), Revision 4 code for a particular organization, business person, or place.', max_length=255, null=True, verbose_name='ISIC V4')),
                ('telephone', models.CharField(blank=True, help_text='The telephone number.', max_length=31, null=True, verbose_name='Telephone')),
            ],
            options={
                'db_table': 'biz_places',
                'verbose_name_plural': 'Places',
                'verbose_name': 'Place',
            },
        ),
        migrations.CreateModel(
            name='PublicPostalAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('alternate_name', models.CharField(blank=True, help_text='An alias for the item.', max_length=255, null=True, verbose_name='Alternate Name')),
                ('description', models.TextField(blank=True, help_text='A short description of the item.', null=True, verbose_name='Description')),
                ('main_entity_of_page', models.URLField(blank=True, help_text='Indicates a page for which this thing is the main entity being described.', null=True, verbose_name='Main Entity Of Page')),
                ('name', models.CharField(blank=True, help_text='The name of the item.', max_length=255, null=True, verbose_name='Name')),
                ('same_as', models.URLField(blank=True, help_text="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Freebase page, or official website.", null=True, verbose_name='Same As')),
                ('url', models.URLField(blank=True, help_text='URL of the item.', null=True, verbose_name='URL')),
                ('address_country', models.CharField(blank=True, help_text='The country. For example, USA. You can also provide the two-letter <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements">ISO 3166-1 alpha-2</a> country code.', max_length=127, null=True, verbose_name='Address Country')),
                ('address_locality', models.CharField(blank=True, help_text='The locality. For example, Mountain View.', max_length=127, null=True, verbose_name='Address Locality')),
                ('address_region', models.CharField(blank=True, help_text='The region. For example, CA.', max_length=127, null=True, verbose_name='Address Region')),
                ('post_office_box_number', models.CharField(blank=True, help_text='The post office box number for PO box addresses.', max_length=127, null=True, verbose_name='Post Office Box Number')),
                ('postal_code', models.CharField(blank=True, help_text='The postal code. For example, 94043.', max_length=127, null=True, verbose_name='Postal Code')),
                ('street_address', models.CharField(blank=True, help_text='The street address. For example, 1600 Amphitheatre Pkwy.', max_length=255, null=True, verbose_name='Street Address')),
                ('image', models.ForeignKey(blank=True, help_text='An image of the item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thing_image_foundation_public_publicpostaladdress_related', to='foundation_public.PublicImageUpload')),
                ('owner', models.ForeignKey(blank=True, help_text='The user whom owns this thing.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'biz_postal_addresses',
                'verbose_name_plural': 'Postal Addresses',
                'verbose_name': 'Postal Address',
            },
        ),
        migrations.AddField(
            model_name='publicplace',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Physical address of the item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_address_foundation_public_publicplace_related', to='foundation_public.PublicPostalAddress'),
        ),
        migrations.AddField(
            model_name='publicplace',
            name='geo',
            field=models.ForeignKey(blank=True, help_text='The geo coordinates of the place.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_geo_foundation_public_publicplace_related', to='foundation_public.PublicGeoCoordinate'),
        ),
        migrations.AddField(
            model_name='publicplace',
            name='image',
            field=models.ForeignKey(blank=True, help_text='An image of the item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thing_image_foundation_public_publicplace_related', to='foundation_public.PublicImageUpload'),
        ),
        migrations.AddField(
            model_name='publicplace',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='An associated logo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_logo_foundation_public_publicplace_related', to='foundation_public.PublicImageUpload'),
        ),
        migrations.AddField(
            model_name='publicplace',
            name='opening_hours_specification',
            field=models.ManyToManyField(blank=True, help_text='The hours during which this service or contact is available.', related_name='place_hours_available_foundation_public_publicplace_related', to='foundation_public.PublicOpeningHoursSpecification'),
        ),
        migrations.AddField(
            model_name='publicplace',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user whom owns this thing.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicplace',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='A photograph of this place.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_photo_foundation_public_publicplace_related', to='foundation_public.PublicImageUpload'),
        ),
        migrations.AddField(
            model_name='publicorganization',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Physical address of the item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_address_foundation_public_publicorganization_related', to='foundation_public.PublicPostalAddress'),
        ),
        migrations.AddField(
            model_name='publicorganization',
            name='brands',
            field=models.ManyToManyField(blank=True, help_text='The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.', related_name='organization_brands_foundation_public_publicorganization_related', to='foundation_public.PublicBrand'),
        ),
        migrations.AddField(
            model_name='publicorganization',
            name='contact_point',
            field=models.ForeignKey(blank=True, help_text='A contact point for a person or organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_contact_point_foundation_public_publicorganization_related', to='foundation_public.PublicContactPoint'),
        ),
        migrations.AddField(
            model_name='publicorganization',
            name='department',
            field=models.ForeignKey(blank=True, help_text='A relationship between an organization and a department of that organization, also described as an organization (allowing different urls, logos, opening hours). For example: a store with a pharmacy, or a bakery with a cafe.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_department_foundation_public_publicorganization_related', to='foundation_public.PublicOrganization'),
        ),
        migrations.AddField(
            model_name='publicorganization',
            name='founding_location',
            field=models.ForeignKey(blank=True, help_text='The place where the Organization was founded.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_founding_location_foundation_public_publicorganization_related', to='foundation_public.PublicPlace'),
        ),
        migrations.AddField(
            model_name='publicorganization',
            name='image',
            field=models.ForeignKey(blank=True, help_text='An image of the item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thing_image_foundation_public_publicorganization_related', to='foundation_public.PublicImageUpload'),
        ),
        migrations.AddField(
            model_name='publicorganization',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='An associated logo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_logo_foundation_public_publicorganization_related', to='foundation_public.PublicImageUpload'),
        ),
        migrations.AddField(
            model_name='publicorganization',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user whom owns this thing.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicorganization',
            name='parent_organization',
            field=models.ForeignKey(blank=True, help_text='The larger organization that this organization is a branch of, if any. Supersedes branchOf.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_parent_foundation_public_publicorganization_related', to='foundation_public.PublicOrganization'),
        ),
        migrations.AddField(
            model_name='publicgeocoordinate',
            name='image',
            field=models.ForeignKey(blank=True, help_text='An image of the item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thing_image_foundation_public_publicgeocoordinate_related', to='foundation_public.PublicImageUpload'),
        ),
        migrations.AddField(
            model_name='publicgeocoordinate',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user whom owns this thing.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publiccountry',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Physical address of the item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_address_foundation_public_publiccountry_related', to='foundation_public.PublicPostalAddress'),
        ),
        migrations.AddField(
            model_name='publiccountry',
            name='geo',
            field=models.ForeignKey(blank=True, help_text='The geo coordinates of the place.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_geo_foundation_public_publiccountry_related', to='foundation_public.PublicGeoCoordinate'),
        ),
        migrations.AddField(
            model_name='publiccountry',
            name='image',
            field=models.ForeignKey(blank=True, help_text='An image of the item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thing_image_foundation_public_publiccountry_related', to='foundation_public.PublicImageUpload'),
        ),
        migrations.AddField(
            model_name='publiccountry',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='An associated logo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_logo_foundation_public_publiccountry_related', to='foundation_public.PublicImageUpload'),
        ),
        migrations.AddField(
            model_name='publiccountry',
            name='opening_hours_specification',
            field=models.ManyToManyField(blank=True, help_text='The hours during which this service or contact is available.', related_name='place_hours_available_foundation_public_publiccountry_related', to='foundation_public.PublicOpeningHoursSpecification'),
        ),
        migrations.AddField(
            model_name='publiccountry',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user whom owns this thing.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publiccountry',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='A photograph of this place.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_photo_foundation_public_publiccountry_related', to='foundation_public.PublicImageUpload'),
        ),
        migrations.AddField(
            model_name='publiccontactpoint',
            name='available_language',
            field=models.ForeignKey(blank=True, help_text='A language someone may use with the item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_point_available_language', to='foundation_public.PublicLanguage'),
        ),
        migrations.AddField(
            model_name='publiccontactpoint',
            name='hours_available',
            field=models.ManyToManyField(blank=True, help_text='The hours during which this service or contact is available.', related_name='contact_point_hours_available', to='foundation_public.PublicOpeningHoursSpecification'),
        ),
        migrations.AddField(
            model_name='publiccontactpoint',
            name='image',
            field=models.ForeignKey(blank=True, help_text='An image of the item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thing_image_foundation_public_publiccontactpoint_related', to='foundation_public.PublicImageUpload'),
        ),
        migrations.AddField(
            model_name='publiccontactpoint',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user whom owns this thing.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicbrand',
            name='image',
            field=models.ForeignKey(blank=True, help_text='An image of the item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thing_image_foundation_public_publicbrand_related', to='foundation_public.PublicImageUpload'),
        ),
        migrations.AddField(
            model_name='publicbrand',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='An associated logo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_logo', to='foundation_public.PublicImageUpload'),
        ),
        migrations.AddField(
            model_name='publicbrand',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user whom owns this thing.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='foundation_public.PublicOrganization'),
        ),
    ]
