# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 18:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foundation_public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicorganization',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='The users that belong to this Organization.', related_name='organization_users_foundation_public_publicorganization_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
