# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-12 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicorganization',
            name='amazon_affiliate_link_url',
            field=models.URLField(blank=True, default='', verbose_name='Amazon Affiliate Link URL'),
        ),
        migrations.AddField(
            model_name='publicorganization',
            name='has_staff_checkin_required',
            field=models.BooleanField(default=True, help_text='Variable controls whether advisor checks are required for moving forward with bizumla creation.', verbose_name='Has staff check-ins required'),
        ),
    ]
