# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_public', '0002_publicorganizationregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicorganizationregistration',
            name='address',
        ),
        migrations.RemoveField(
            model_name='publicorganizationregistration',
            name='contact_point',
        ),
        migrations.RemoveField(
            model_name='publicorganizationregistration',
            name='users',
        ),
    ]
