# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_num', models.PositiveSmallIntegerField(db_index=True, default=1, help_text='Track what stage this lecture belongs to.', verbose_name='Stage Number')),
                ('title', models.CharField(blank=True, help_text='The name of the City.', max_length=127, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', help_text='A short description of the item.', null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='The name of the City.', max_length=31, null=True, verbose_name='Icon')),
                ('colour', models.CharField(blank=True, help_text='The name of the City.', max_length=31, null=True, verbose_name='Colour')),
            ],
            options={
                'verbose_name': 'Lecture',
                'verbose_name_plural': 'Lectures',
                'db_table': 'biz_lectures',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.PositiveSmallIntegerField(db_index=True, default=1, help_text='The page number in the slides for the lecture.', verbose_name='Page Number')),
                ('intro_title', models.CharField(blank=True, help_text='The name of the City.', max_length=255, null=True, verbose_name='Introduction Title')),
                ('intro_description', models.TextField(blank=True, default='', help_text='A short description of the item.', null=True, verbose_name='Introduction Description')),
                ('video', models.FileField(blank=True, help_text='An file of the upload.', null=True, upload_to='upload', verbose_name='File')),
                ('outro_title', models.CharField(blank=True, help_text='The name of the City.', max_length=255, null=True, verbose_name='Outro Title')),
                ('outro_description', models.TextField(blank=True, default='', help_text='A short description of the item.', null=True, verbose_name='Outro Description')),
                ('lecture', models.ForeignKey(blank=True, help_text='The lecture this slide belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slide_lecture_tenant_bizmula_slide_related', to='tenant_bizmula.Lecture')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slide',
                'db_table': 'biz_slides',
            },
        ),
    ]
