# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_bizmula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_num', models.PositiveSmallIntegerField(db_index=True, default=1, help_text='Track what stage this Module belongs to.', verbose_name='Stage Number')),
                ('start_slide_id', models.PositiveSmallIntegerField(blank=True, default=0, help_text='The start slide ID to begin with.', null=True, verbose_name='Start Slide ID')),
                ('title', models.CharField(blank=True, help_text='The name of the City.', max_length=127, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', help_text='A short description of the item.', null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='The name of the City.', max_length=31, null=True, verbose_name='Icon')),
                ('colour', models.CharField(blank=True, help_text='The name of the City.', max_length=31, null=True, verbose_name='Colour')),
            ],
            options={
                'verbose_name': 'Module',
                'db_table': 'biz_modules',
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='lecture',
        ),
        migrations.AlterField(
            model_name='slide',
            name='page_num',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, help_text='The page number in the slides for the module.', verbose_name='Page Number'),
        ),
        migrations.AlterModelTable(
            name='exercise',
            table='biz_exercises',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.AddField(
            model_name='exercise',
            name='module',
            field=models.ForeignKey(blank=True, help_text='The module this Exercise belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_module_tenant_bizmula_exercise_related', to='tenant_bizmula.Module'),
        ),
        migrations.AddField(
            model_name='slide',
            name='module',
            field=models.ForeignKey(blank=True, help_text='The module this slide belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slide_module_tenant_bizmula_slide_related', to='tenant_bizmula.Module'),
        ),
    ]
