# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _


# Array of suspicious URLs which are generally called by Users who have
# malicious intent to harm our system.
SUSPICIOUS_PATHS = [
    '/phpmyadmin/scripts/setup.php',
    '/phpMyAdmin/scripts/setup.php',
    '/pma/scripts/setup.php',
    '/myadmin/scripts/setup.php',
    '/OnlineUpdate/questions.php',
    '/phpmyadmin',
    '/HNAP1/',
    '/wp-login.php',
    '/administrator/index.php',
    '/administrator',
    '/manager/html',
    '/ip_json.php',
    '/hndUnblock.cgi',
    '/tmUnblock.cgi',
    '/cgi/common.cgi',
    '/stssys.htm',
    '/admin/config.php',
    '/check_proxy',
    '/muieblackcat',
    '/pma/scripts/setup.php',
    '/CHANGELOG.txt',
    '/readme.html',
    '/.git/HEAD',
    '/zabbix/index.php',
    '/xmlrpc.php',
    '/r/errors.log',
    '/license.php',
    '/web-console/ServerInfo.jsp',
    '/jmx-console',
    '/if youve had a dose of a freaky ghost',
    '/invoker/JMXInvokerServlet',
    '/status',
    '/engine/log.txt',
    '/command.php',
    '/wp-includes/js/wp-util.js',
    '/benutzer/env.cgi',
    '/1phpmyadmin/',
    '/cgi-bin/nobody',
    '/OA_HTML/OA.jsp',
    '/unAuthorizedAccess.action',
    '/loginAction!login.action',
    '/Main.action',
    '/doLogin.do',
    '/login.do',
    '/loginUI.action',
    '/index.login.action',
    '/adminManager!login',
    '/etc/lib/pChart2/examples/index.php?Action=View&Script=../../../../cnf/db.php',
    '/language/Swedish${IFS}&&echo${IFS}610cker>qt&&tar${IFS}/string.js',
    '/fckeditor/fckeditor.js',
    '\xF3\xA1\x05,\x0C^\xFA\xD3C\x0BX\xE6\xC6W\xE8YR\x14r\xD32\x1E\x05\xC8\xD8=x\xB6K\x19\xD0\xA0\xBD\xCE\xEE\xF2No\xD6\xF17\x04Cs\x0E;\x94\xBB\xE7\x05\xF1k\xAB\xCDy\x13\xD6uk\xD7\x12\x8BA\x09',
    '\x04\x01\x00P\xB4\xA3qR\x00',
    '/cgi-bin/nobody/Machine.cgi',
    '\x00',
    '\x04\x01\x00P\xC0c\xF660\x00',
    '\x05\x02\x00\x02',
    '/w00tw00t.at.ISC.SANS.DFind:)',
    '/x',
    '/jenkins/script',
    '/msd',
    '/mysqldumper',
    '/mySqlDumper',
    '/msd1.24stable',
    '/msd1.24.4',
    '/mysql',
    '/sql',
    '/sqlite',
    '/SQLite',
    '/SQLiteManager',
    '/cgi-bin',
    '/cgi-mod',
    '/cgi-sys',
    '/wp-admin',
    '/admin.php',
    '/Http/DataLayCfg.xml',
    '/www/start.html',
    '/RemoteControl.html',
    '/functions.php',
    '/sqlibak.php'
]
